name: halal_admin
description: Dashboard pour restaurateurs - Gestion visibilité et abonnements
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Firebase (existant)
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  
  # Firebase (nouveau pour algorithme)
  cloud_functions: ^5.1.3
  
  # Géolocalisation
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # Paiements Stripe
  flutter_stripe: ^11.2.0
  url_launcher: ^6.3.1
  
  # UI & Charts
  fl_chart: ^0.69.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  
  # Utilitaires
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.2.2
  
  # Maps (pour widget carte rayon)
  # google_maps_flutter: ^2.9.0  # Décommenter si besoin
  # flutter_map: ^7.0.2  # Alternative OpenStreetMap

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/landing/
    - assets/icons/
  
  # Fonts commentées (fichier manquant)
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: fonts/CustomIcons.ttf