// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions not configured for macOS');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions not configured for Windows');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions not configured for Linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions not supported for this platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7O8J9VA9tKyDufwikP4084m1Msm5Xvk4',
    appId: '1:847039931012:web:c09d8234690e21697998d1',
    messagingSenderId: '847039931012',
    projectId: 'halal4329',
    authDomain: 'halal4329.firebaseapp.com',
    storageBucket: 'halal4329.firebasestorage.app',
    measurementId: 'G-RPPTKZ0W28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7O8J9VA9tKyDufwikP4084m1Msm5Xvk4',
    appId: '1:847039931012:android:47035a23dbae80c87998d1',
    messagingSenderId: '847039931012',
    projectId: 'halal4329',
    storageBucket: 'halal4329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7O8J9VA9tKyDufwikP4084m1Msm5Xvk4',
    appId: '1:847039931012:ios:7a654ea3894886737998d1',
    messagingSenderId: '847039931012',
    projectId: 'halal4329',
    storageBucket: 'halal4329.firebasestorage.app',
    iosBundleId: 'com.example.monHalalApp',
  );
}
